### PR TITLE
Add missing comma in request_headers dict

### PR DESCRIPTION
**Pull request by oaosman84**
This was throwing `invalid syntax` errors

### CODE REVIEW

**Review by belkka — APPROVED** [review]

**Review by belkka — APPROVED** [review]

**Review by belkka — APPROVED** [review]
Wow, I didn't know that I can approve same changes several times

**Comment by oaosman84** [comment]
How do we merge this?

**Comment by belkka** [comment]
:man_shrugging:

**Review by belkka — APPROVED** [review]

**Comment by belkka** [comment]
I don't think approving the same changes several times has any effect

**Comment by oaosman84** [comment]
It says only those with "write access" to this repository can merge pull requests.

image

**Comment by belkka** [comment]
@genesluder

**Pull request merged**
